### ISSUE TITLE
Work out tagging/versioning scheme

### ISSUE THREAD

**Issue by bo0tzz** [bo0tzz/cnpgvecto.rs#3]
Some options:
* Directly copy the (postgres version) tags from the cnpg images: `15`, `16`, `16.1`, etc., always with the latest pgvecto.rs version (at build time).
* Include the pgvecto.rs version in the tags: `15-v0.1.8`, `16.1-v0.1.7`, etc. 
* ???
* Both?

**Comment by samip5** [comment]
I think including pgvecto.rs version in tag is probably a good idea. 🤔

**Comment by bo0tzz** [comment]
This is what I've decided to go with for the tags. I'm closing this issue, but any comments on the scheme are still welcome.

![image](https://github.com/bo0tzz/cnpgvecto.rs/assets/11602424/d580c256-ecc9-4636-a841-b928d8174722)
