### ISSUE TITLE
Extension is not loadable without restart of Postgres cluster

### ISSUE THREAD

**Issue by samip5** [bo0tzz/cnpgvecto.rs#6]
It appears that the extension doesn't load without needing a restart of cnpg, it should probably be automated somehow.

**Comment by bo0tzz** [comment]
Per the cnpg docs (https://cloudnative-pg.io/documentation/1.20/postgresql_conf/#shared-preload-libraries):
> You can provide additional shared_preload_libraries via .spec.postgresql.shared_preload_libraries as a list of strings: the operator will merge them with the ones that it automatically manages.

Would that work maybe?

Besides that - I can't find anything that indicates adding to shared_preload_libraries requires a restart, and iirc in my testing (on just a local docker container) it worked without a restart as well. Any idea why cnpg might be wanting this?

Finally, just for clarification: is it the postgres cluster that wants a restart (which is what I assume) or the cnpg controller?

**Comment by samip5** [comment]
The postgres cluster, NOT the operator.
