### ISSUE TITLE
permission denied to create extension "vectors"

### ISSUE THREAD

**Issue by bo0tzz** [bo0tzz/cnpgvecto.rs#7]
I think this is just a database role permissions thing, but if there's anything that can be done to automatically load this from the container image side that would be great.

**Comment by bo0tzz** [comment]
After creating the extension manually, immich-server errors with `must be owner of extension vectors`

**Comment by samip5** [comment]
Can we give Immich user the perms to do it without full superuser privileges?

**Comment by bo0tzz** [comment]
It seems like pgvecto.rs operates on a pretty low level, and thus the extension is essentially "a database superuser on steroids" (to quote [supabase](https://supabase.com/blog/pg-tle#trusted-vs-untrusted). As such the security model is set up so that only superusers can use it, it seems. You could argue that since the db admin has installed and vetted the extension, they should be able to assign permissions to a role to use that extension, but I don't see any way to do that.

**Comment by bo0tzz** [comment]
I tried doing the following:
1. Initialize a db cluster for Immich
2. Connect to it manually and run
```sql
ALTER ROLE immich WITH SUPERUSER;
SET ROLE immich;
CREATE EXTENSION vectors;
RESET ROLE;
ALTER ROLE immich WITH NOSUPERUSER;
```
3. Start the Immich containers and let them run migrations.

This didn't work because during the migrations they still call `CREATE EXTENSION vectors` and fail with a permission issue.

Next I tried giving `SUPERUSER` to the immich role only during the migrations, and then taking it away after everything started up. That seems to work OK, with the machine-learning features all still working correctly after taking away the permission, including alterations to the vector tables when updating the CLIP model. Restarting the containers also didn't cause any issues.

**Comment by samip5** [comment]
That seems like a PITA to do in app init. :D

**Comment by bo0tzz** [comment]
Strong agree!

**Comment by bo0tzz** [comment]
It seems like at least a part of this is caused because the Immich migration starts by running `DROP EXTENSION IF EXISTS vectors`. That immediately fails due to not being a superuser. We should be able to remove that line and just use `CREATE EXTENSION IF NOT EXISTS vectors` (seems like in the past pgvecto.rs did not support that). 

With that, some manual action will unfortunately still be needed to create the extension ahead of time, but it'll be as straightforward as just connecting to the database with a superuser and running `CREATE EXTENSION vectors`.

**Comment by samip5** [comment]
Why is there that in the first place?

**Comment by bo0tzz** [comment]
The pgvecto.rs docs suggest it, and apparently in the past IF NOT EXISTS was not supported by pgvecto.rs?

**Comment by Rahulsharma0810** [comment]
> I tried doing the following:
> 
> 1. Initialize a db cluster for Immich
> 2. Connect to it manually and run
> 
> ```sql
> ALTER ROLE immich WITH SUPERUSER;
> SET ROLE immich;
> CREATE EXTENSION vectors;
> RESET ROLE;
> ALTER ROLE immich WITH NOSUPERUSER;
> ```
> 
> 3. Start the Immich containers and let them run migrations.
> 
> This didn't work because during the migrations they still call `CREATE EXTENSION vectors` and fail with a permission issue.
> 
> Next I tried giving `SUPERUSER` to the immich role only during the migrations, and then taking it away after everything started up. That seems to work OK, with the machine-learning features all still working correctly after taking away the permission, including alterations to the vector tables when updating the CLIP model. Restarting the containers also didn't cause any issues.

Step to achieve this.
- ALTER USER "postgresql-immich-pgsql" WITH SUPERUSER;
- Run Immich or use [helm](https://github.com/immich-app/immich-charts).
- Wait for Up.
- ALTER USER "postgresql-immich-pgsql" WITH NOSUPERUSER;
